export default {
  login: "govind-kumarr",
  id: 106414173,
  node_id: "U_kgDOBlfAXQ",
  avatar_url: "https://avatars.githubusercontent.com/u/106414173?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/govind-kumarr",
  html_url: "https://github.com/govind-kumarr",
  followers_url: "https://api.github.com/users/govind-kumarr/followers",
  following_url:
    "https://api.github.com/users/govind-kumarr/following{/other_user}",
  gists_url: "https://api.github.com/users/govind-kumarr/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/govind-kumarr/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/govind-kumarr/subscriptions",
  organizations_url: "https://api.github.com/users/govind-kumarr/orgs",
  repos_url: "https://api.github.com/users/govind-kumarr/repos",
  events_url: "https://api.github.com/users/govind-kumarr/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/govind-kumarr/received_events",
  type: "User",
  site_admin: false,
  name: "Govind Kumar",
  company: "Masai School",
  blog: "https://govind-kumarr.github.io/",
  location: "Kangra, HImachal Pradesh",
  email: null,
  hireable: null,
  bio: "Aspiring Full stack Web Developer.",
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 91,
  following: 180,
  created_at: "2022-05-28T00:55:41Z",
  updated_at: "2022-11-16T14:55:59Z",
};